Jackson Parameter Names module
opentable/otj-jackson pull request #4
Opened 2016-12-30 18:07 UTC by stevenschlansker

2016-12-30 18:33 UTC, stevenschlansker commented
Check failure due to https://github.com/ning/maven-dependency-versions-check-plugin/pull/11 not being merged yet.  Pinged Henning to see if he will merge it.

2017-01-04 17:40 UTC, pennello requested changes

2017-01-04 17:40 UTC, pennello commented on pom.xml
> +    <version>72-SNAPSHOT</version>
Still snapshot.

2017-01-04 17:40 UTC, pennello commented on src/test/java/com/opentable/jackson/TestOpenTableJacksonConfiguration.java
> +    }
Test the negative as well?

2017-01-10 23:25 UTC, merged